apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: npn-rag-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: api.npn-rag.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: npn-rag-service
                port:
                  number: 8000
