apiVersion: v1
kind: Service
metadata:
  name: npn-rag-service
  namespace: default
  labels:
    app: npn-rag-engine
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: npn-rag-engine
